;=================================================================
; Procedure:	ReadCharA
;
; Calling Convention:	__stdcall
;
; Description:
;	Reads a single ANSI character from the standard input.
;	Removes the trailing CR/LF generated by <ENTER>
;
; Parameters:	
;	None
;
; Returns:
;	- AL/EAX contains the input character if the given input is
;		not empty.
;	- If Input read error, EAX will contain -1
;=================================================================

ReadCharA	PROC STDCALL
	call ConsoleLoadInputInBuffer

	cmp eax, 0
	jl Epilogue

	mov ecx, __console.stdIn.position
	movzx eax, BYTE PTR [__console.stdIn.buffer+ecx]
	inc __console.stdIn.position

Epilogue:
	ret
ReadCharA	ENDP