;=================================================================
; Procedure:	ReadLineA
;
; Calling Convention:	__stdcall
;
; Description:
;	Reads a line of ANSI characters from the standard input.
;	Removes the trailing CR/LF generated by <ENTER>
;
; Parameters:	
;	- lpBuffer:		LPSTR -- A buffer to store the input line
;	- nBufferSize:	DWORD -- Total size of buffer including '\0'
;
; Returns:
;   Success:
;       lpBuffer receives a null-terminated ANSI string.
;       EAX = Length of the string (excluding '\0').
;
;   Failure:
;       EAX = -1.
;       Contents of lpBuffer are undefined.
;
; Remarks:
;	Since the procedure appends the string with a '\0' at the
;	end make sure to pass nBufferSize accordingly.
;	For example: If you pass buffer size as 5 and you type Hello
;		then following cases should be considered:
;		Case-1:
;			0 1 2 3 4
;			H e l l []
;			lpBuffer[4] = \0
;			string size = eax = 4
;
;		Case-2:
;			0 1 2 3   4
;			H e CR LF []
;			lpBuffer[2] = \0
;			string size = eax = 2
;
;		Case-3:
;			0 1 2 3  4
;			H e l CR []
;			lpBuffer[3] = \0
;			string size = eax = 3
;=================================================================

ReadLineA	PROC STDCALL,
	lpBuffer:		LPSTR,
	nBufferSize:	DWORD

	push ebx

	call ConsoleLoadInputInBuffer

	cmp eax, 0
	jl Epilogue

	mov edx, lpBuffer					; EDX = lpBuffer
	xor ecx, ecx						; ECX = current length of lpBuffer string

@@:
	mov eax, __console.stdIn.position
	cmp eax, __console.stdIn.nLength
	je	AppendNullTerminator
	
	cmp ecx, nBufferSize
	je AppendNullTerminator

	mov ebx, __console.stdIn.position
	mov al, BYTE PTR [__console.stdIn.buffer+ebx]
	mov BYTE PTR [edx+ecx], al
	
	inc __console.stdIn.position	; move cursor of input buffer
	inc ecx							; move cursor of lpBuffer
	jmp @B

AppendNullTerminator:
	mov BYTE PTR [edx+ecx], 0		; \0 at end of string
	mov eax, ecx					; EAX = total length of string (line)

Epilogue:
	pop ebx
	ret

ReadLineA	ENDP